#!/usr/bin/env bash
set -eu

manifests=()

walk_dir () {
    for pathname in "$1"/*; do
        if [ -d "$pathname" ]; then
            walk_dir "$pathname"
        else
            manifests+=("$pathname")
        fi
    done

}

prepare_skaffold_conf() {

walk_dir "microstream-infra/src/app/rendered/1-manifest"

local nl
nl=$'\n'

local str_manifest

local lines
for each in ${manifests[*]}
do
  lines+=("     - $each $nl")
done

str_manifest="${lines[*]}"

# local ymlConf
(
  cat <<EOF
# do not edit, this file was autogenerated by $0
apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: microstream
build:
  artifacts:
    - image: localhost:5000/microstream-be
      context: microstream-be
      docker:
        dockerfile: dev.Dockerfile
      sync:
        infer:
          - "**/*.{scala,conf,sbt,xml,json,sql}"
    - image: localhost:5000/microstream-fe
      context: microstream-fe
      docker:
        dockerfile: dev.Dockerfile
      sync:
        infer:
          - "**/*.{js,jsx,ts,tsx,css,scss,html,json}"
deploy:
  kubectl:
    manifests:
$str_manifest
EOF
) > skaffold.yml
}

rm -f skaffold.yaml
prepare_skaffold_conf